#ifndef ISR_CONFIG_H
#define ISR_CONFIG_H

#define ISR_PRIORITY_SERIAL_ERROR   (0)
#define ISR_PRIORITY_SERIAL_WRITE   (1)
#define ISR_PRIORITY_SERIAL_READ    (2)

#define ISR_PRIORITY_CAN_COMM_ERROR (3)
#define ISR_PRIORITY_CAN_MSG_LOST   (4)
#define ISR_PRIORITY_CAN_MSG_RCVD   (5)
#define ISR_PRIORITY_CAN_MSG_SENT   (6)

#endif /* ISR_CONFIG_H */
