#ifndef ISR_CONFIG_H
#define ISR_CONFIG_H

#define ISR_PRIORITY_SERIAL_TX (0)
#define ISR_PRIORITY_SERIAL_RX (1)
#define ISR_PRIORITY_SERIAL_ER (2)

#define ISR_PRIORITY_CAN_TX_BUFFER (5)
#define ISR_PRIORITY_CAN_RX_BUFFER (4)

#endif /* ISR_CONFIG_H */
